on: 
  push:
    tags:
      - v*

name: Publish to crates.io

permissions:
    contents: write

jobs:
  check:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Hack publish-crates to not fail on paths
        run: |
          sed 's/, path = ".*"//' -i Cargo.toml
          sed '/redis-macros = { path = ".." }/d' -i redis-macros-derive/Cargo.toml
      - uses: katyo/publish-crates@v2
        with:
          path: ./redis-macros-derive
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
          args: --allow-dirty
      - uses: katyo/publish-crates@v2
        with:
          path: ./
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          args: --allow-dirty
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: Changelog.md
          token: ${{ secrets.GITHUB_TOKEN }}

